-- =========================================================
--  리뷰 좋아요(BR_COMMENT_LIKE) + 찜하기(BR_WISHLIST)
--  접속 계정 : hr / hr
--  book_review.sql, comment.sql 실행 후 한 번만 실행하세요.
-- =========================================================

-- ── 1) 리뷰 좋아요 ──────────────────────────────────────
DROP TABLE BR_COMMENT_LIKE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BR_COMMENT_LIKE_NO;

CREATE TABLE BR_COMMENT_LIKE (
    NO          NUMBER  PRIMARY KEY,
    MEMBER_NO   NUMBER  NOT NULL,
    COMMENT_NO  NUMBER  NOT NULL,
    REG_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_CLIKE_MEMBER  FOREIGN KEY (MEMBER_NO)  REFERENCES BR_MEMBER (NO)  ON DELETE CASCADE,
    CONSTRAINT FK_CLIKE_COMMENT FOREIGN KEY (COMMENT_NO) REFERENCES BR_COMMENT (NO) ON DELETE CASCADE,
    CONSTRAINT UQ_CLIKE UNIQUE (MEMBER_NO, COMMENT_NO)   -- 한 리뷰에 회원당 1회
);
CREATE SEQUENCE SEQ_BR_COMMENT_LIKE_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_CLIKE_COMMENT ON BR_COMMENT_LIKE (COMMENT_NO);
CREATE INDEX IDX_CLIKE_MEMBER  ON BR_COMMENT_LIKE (MEMBER_NO);

-- ── 2) 찜하기 ──────────────────────────────────────────
DROP TABLE BR_WISHLIST CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_BR_WISHLIST_NO;

CREATE TABLE BR_WISHLIST (
    NO          NUMBER  PRIMARY KEY,
    MEMBER_NO   NUMBER  NOT NULL,
    BOOK_NO     NUMBER  NOT NULL,
    REG_DATE    DATE    DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_WISH_MEMBER FOREIGN KEY (MEMBER_NO) REFERENCES BR_MEMBER (NO) ON DELETE CASCADE,
    CONSTRAINT FK_WISH_BOOK   FOREIGN KEY (BOOK_NO)   REFERENCES BR_BOOK (NO),
    CONSTRAINT UQ_WISH UNIQUE (MEMBER_NO, BOOK_NO)       -- 같은 책 중복 찜 방지
);
CREATE SEQUENCE SEQ_BR_WISHLIST_NO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE INDEX IDX_WISH_MEMBER ON BR_WISHLIST (MEMBER_NO);

COMMIT;

-- 확인
-- SELECT * FROM BR_COMMENT_LIKE;
-- SELECT * FROM BR_WISHLIST;
